#!/usr/bin/env python3
"""Generate the optimized Launch System ERD as an uncompressed draw.io file.

The model targets PostgreSQL 16+.  It intentionally separates immutable facts
and events from mutable workflow aggregates and labels unresolved business
rules instead of silently inventing them.
"""

from __future__ import annotations

import argparse
import math
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
import xml.etree.ElementTree as ET


@dataclass(frozen=True)
class Node:
    name: str
    module: str
    fields: tuple[str, ...] = ()
    kind: str = "table"  # table, view, module, note
    text: str = ""


@dataclass(frozen=True)
class Rel:
    parent: str
    child: str
    label: str = "1 to 0..*"
    dashed: bool = False


@dataclass
class Page:
    name: str
    subtitle: str
    nodes: list[Node] = field(default_factory=list)
    relations: list[Rel] = field(default_factory=list)
    notes: list[Node] = field(default_factory=list)


def T(name: str, module: str, *fields: str) -> Node:
    return Node(name, module, tuple(fields), "table")


def V(name: str, module: str, *fields: str) -> Node:
    return Node(name, module, tuple(fields), "view")


def M(name: str, module: str, text: str) -> Node:
    return Node(name, module, (), "module", text)


def N(title: str, text: str, module: str = "note") -> Node:
    return Node(title, module, (), "note", text)


PALETTE = {
    "iam": ("#E8F1FB", "#6C8EBF", "#1F4E79"),
    "po": ("#FFF1E6", "#D79B00", "#8A4B08"),
    "bom": ("#F2E9FF", "#9673A6", "#5B3B72"),
    "inventory": ("#EAF6EA", "#82B366", "#2F6B2F"),
    "delivery": ("#E5F6F6", "#4FA3A5", "#1D6668"),
    "finance": ("#FFF6D9", "#D6B656", "#7A5C00"),
    "audit": ("#FBE8E7", "#B85450", "#7F2420"),
    "cross": ("#EDF1F5", "#7B8A97", "#34495E"),
    "note": ("#FFF9D9", "#D6B656", "#5F4B00"),
}


def build_pages() -> list[Page]:
    pages: list[Page] = []

    pages.append(Page(
        "00 Review/Assumptions",
        "Verdict, PostgreSQL conventions, resolved design gaps, and business decisions still required.",
        notes=[
            N("Review verdict", "The supplied DBML is a useful first draft but is not production-ready. It mixes mutable balances with history, keys PO lines by version, models BOM changes as intervals rather than full snapshots, and lacks reproducible policy snapshots, exact-once inventory posting, signer identity, sessions, outbox delivery, and tamper-evident audit chaining. This ERD corrects those structural gaps."),
            N("PostgreSQL 16+ conventions", "Use uuid identifiers (prefer UUIDv7 generated by the application or an approved extension), timestamptz in UTC for instants, date for business dates, numeric(20,4) for quantities/prices, char(n) only for confirmed fixed-length codes, jsonb only for immutable snapshots/payloads, and object storage for file bytes. Enable RLS by project and revoke UPDATE/DELETE on append-only tables."),
            N("Stable facts vs projections", "PO versions, BOM revisions, launch items, partial-production events, inventory postings, status history, confirmations, signatures, price/cost periods, and audit events are immutable facts. Current PO progress, stock balances, actual sales, revenue, threshold state, and dashboards are views/materialized projections. Never repair history by overwriting a fact; append a correction/reversal."),
            N("Major reconciliations", "Stable purchase_order_items survive every PO version and join typed launch, production, and confirmed-delivery facts. All 20 extracted fields retain validation detail; immutable PO rows snapshot customer/contact/FGPN/development labels. BOM revisions are complete xlsx snapshots. Simulations snapshot multi-PO progress plus warehouse/WIP/transit/planned stock and dated future arrivals."),
            N("Inventory correctness", "Locations belong to explicit stock pools and project_stock_pools defines shared versus project-scoped access. Every stock-changing command creates one inventory_event and immutable signed postings atomically. UNIQUE source/idempotency keys plus payload_hash give exactly-once acceptance. Balance views are projections, never manually edited."),
            N("Documents and audit", "documents stores immutable SHA-256 metadata, an external KMS key/version reference, and retention/legal-hold controls. Domain rows hold normal FKs to documents; signatures retain typed signer identity and display snapshot. audit_events is append-only and hash-chained, and outbox_events commits with the business fact."),
            N("Open points OP-01 to OP-04", "OP-01 FGPN length remains configurable; no false length CHECK is imposed until a real example is approved. OP-02/03/04 role scope remains policy data through permissions, role_permissions, one temporal active user role, temporal project assignments, and server-side RLS. Plant Manager stays read-only, Launch Manager writes assigned projects, and Warehouse Personnel remains least-privilege pending confirmation."),
            N("Open points OP-05 to OP-09", "OP-05 status moves are unique from/to rows with allowed roles in po_status_transition_roles; backward moves require a reason. OP-06 priority/tie-break rules are immutable simulation policy versions. OP-07 confirmation requires explicit evidence, with accepted form configurable. OP-08 delivery methods are typed master data. OP-09 safety coefficient defaults to 2 only as versioned policy data."),
            N("Open points OP-10 to OP-13", "OP-10 signed warehouse receipt validation stores validator and time before the inventory event is posted. OP-11 invoice requirement is a system setting/policy rule. OP-12 future-simulation drafts are persisted as documents. OP-13 code TTL is a setting seeded to 48 hours until business sign-off; codes are hashed, unique, expiring, and single-use."),
            N("Key data rules", "PO number: char(10), length 10. PO part number: char(7). Color code: char(4). PO level: varchar(6). Unit price and quantities: numeric(20,4), non-negative/positive as appropriate. Descriptions: varchar(50). Material part number: varchar(10). PO/BOM/CutMan/signed/invoice file formats are enforced by domain checks plus content sniffing; CutMan SQL is parsed as data and never executed."),
            N("Concurrency and lifecycle", "Mutable aggregates carry row_version bigint for optimistic locking. user_sessions implements the configurable 60-minute inactivity timeout and revocation. Deactivate reference/users instead of deleting. Deferred constraint triggers enforce cross-table rules such as same-project references, final launch meeting minutes, confirmation before Delivered, and delivered quantity not exceeding the current ordered quantity."),
            N("Legend", "Blue IAM/reference | Orange PO | Purple BOM/simulation | Green inventory | Teal deliveries | Gold finance | Red audit | Grey views/projections | Yellow invariants/open decisions. PK/FK/UQ/CK/IX/GEN mean primary key, foreign key, unique, check, index, and generated value."),
        ],
    ))

    overview_nodes = [
        M("IAM & project scope", "iam", "users, sessions, roles, assignments, references, documents"),
        M("PO intake & versions", "po", "PDF audit copy, extraction review, stable items, immutable versions, status"),
        M("BOM & simulation", "bom", "xlsx full snapshots, policy snapshots, multi-PO allocation, launch gate"),
        M("Inventory ledger", "inventory", "pools + locations, exact-once events/postings, CutMan, arrivals"),
        M("Warehouse transfer", "delivery", "meeting-gated instruction lines, one-time code, signed receipt"),
        M("Customer delivery", "delivery", "instruction, partial shipments, explicit confirmation evidence"),
        M("Finance", "finance", "effective prices/costs, immutable delivery snapshots, forecast vs actual"),
        M("Audit & integration", "audit", "hash chain, traceability package, alerts, transactional outbox"),
        V("v_operational_dashboard", "cross", "project-scoped exception panels", "PO / stock / launch / delivery / finance"),
    ]
    pages.append(Page(
        "01 Overview",
        "End-to-end business flow. Detailed tables and constraints are on pages 02-07.",
        nodes=overview_nodes,
        relations=[
            Rel("IAM & project scope", "PO intake & versions", "authorizes / scopes"),
            Rel("PO intake & versions", "BOM & simulation", "versioned demand"),
            Rel("BOM & simulation", "Inventory ledger", "reads snapshots"),
            Rel("BOM & simulation", "Warehouse transfer", "approved launch"),
            Rel("Inventory ledger", "Warehouse transfer", "posts transfer"),
            Rel("Warehouse transfer", "Customer delivery", "manufactured goods"),
            Rel("Customer delivery", "Finance", "confirmed shipment facts"),
            Rel("Finance", "Audit & integration", "financial events"),
            Rel("IAM & project scope", "Audit & integration", "actor/session facts"),
            Rel("PO intake & versions", "Audit & integration", "immutable facts"),
            Rel("BOM & simulation", "Audit & integration", "decision basis"),
            Rel("Inventory ledger", "Audit & integration", "ledger facts"),
            Rel("Customer delivery", "Audit & integration", "confirmation evidence"),
            Rel("Audit & integration", "v_operational_dashboard", "event-fed projections", True),
        ],
        notes=[N("Boundary rule", "Every operational row is project-scoped directly or through a mandatory FK path. Server-side authorization/RLS uses project_assignments; UI hiding is not a security control.")],
    ))

    pages.append(Page(
        "02 IAM/Projects/References/Documents",
        "Identity, access scope, durable reference data, sessions, files, and signer identity.",
        nodes=[
            T("roles", "iam", "PK id smallint", "UQ code role_code NOT NULL", "name varchar(80) NOT NULL", "active boolean NOT NULL DEFAULT true"),
            T("permissions", "iam", "PK id smallint", "UQ code permission_code NOT NULL", "name varchar(120) NOT NULL", "description text NULL", "active boolean NOT NULL DEFAULT true"),
            T("role_permissions", "iam", "FK role_id smallint NOT NULL -> roles", "FK permission_id smallint NOT NULL -> permissions", "PK (role_id,permission_id)", "FK granted_by uuid NULL -> users", "granted_at timestamptz NOT NULL", "CK rows are append-only policy data"),
            T("users", "iam", "PK id uuid", "FK current_role_id smallint NULL -> roles", "UQ username citext NOT NULL", "password_hash text NOT NULL", "status user_status NOT NULL", "failed_login_count smallint NOT NULL DEFAULT 0", "locked_at timestamptz NULL", "deactivated_at timestamptz NULL", "row_version bigint NOT NULL DEFAULT 1", "created_at timestamptz NOT NULL", "CK active user has exactly one open role assignment", "CK current_role_id is a trigger-checked cache"),
            T("user_role_assignments", "iam", "PK id uuid", "FK user_id uuid NOT NULL -> users", "FK role_id smallint NOT NULL -> roles", "FK assigned_by uuid NOT NULL -> users", "assigned_at timestamptz NOT NULL", "FK ended_by uuid NULL -> users", "ended_at timestamptz NULL", "reason text NULL", "UQ partial user_id WHERE ended_at IS NULL", "CK ended_at>assigned_at when set; immutable history"),
            T("user_sessions", "iam", "PK id uuid", "FK user_id uuid NOT NULL -> users", "UQ token_digest bytea NOT NULL", "created_at timestamptz NOT NULL", "last_seen_at timestamptz NOT NULL", "expires_at timestamptz NOT NULL", "revoked_at timestamptz NULL", "ip_address inet NULL", "user_agent text NULL", "CK expires_at > created_at"),
            T("login_events", "iam", "PK id bigint GENERATED IDENTITY", "FK user_id uuid NULL -> users", "username_entered citext NOT NULL", "success boolean NOT NULL", "failure_reason varchar(80) NULL", "occurred_at timestamptz NOT NULL", "ip_address inet NULL", "IX (username_entered, occurred_at)"),
            T("customers", "iam", "PK id uuid", "UQ customer_code varchar(40) NOT NULL", "legal_name varchar(180) NOT NULL", "display_name varchar(150) NOT NULL", "active boolean NOT NULL DEFAULT true", "row_version bigint NOT NULL DEFAULT 1", "created_at timestamptz NOT NULL"),
            T("customer_contacts", "iam", "PK id uuid", "FK customer_id uuid NOT NULL -> customers", "contact_code varchar(60) NOT NULL", "full_name varchar(150) NOT NULL", "email citext NULL", "phone varchar(40) NULL", "active boolean NOT NULL DEFAULT true", "row_version bigint NOT NULL DEFAULT 1", "UQ (customer_id,contact_code)"),
            T("manufacturing_receivers", "iam", "PK id uuid", "UQ receiver_code varchar(60) NOT NULL", "FK user_id uuid NULL -> users", "full_name varchar(150) NOT NULL", "organization varchar(150) NULL", "active boolean NOT NULL DEFAULT true", "row_version bigint NOT NULL DEFAULT 1"),
            T("delivery_methods", "iam", "PK id uuid", "UQ method_code varchar(40) NOT NULL", "name varchar(120) NOT NULL", "active boolean NOT NULL DEFAULT true", "row_version bigint NOT NULL DEFAULT 1"),
            T("material_types", "iam", "PK id uuid", "UQ type_code varchar(40) NOT NULL", "name varchar(120) NOT NULL", "active boolean NOT NULL DEFAULT true", "row_version bigint NOT NULL DEFAULT 1"),
            T("projects", "iam", "PK id uuid", "UQ project_code varchar(30) NOT NULL", "project_name varchar(150) NOT NULL", "FK customer_id uuid NOT NULL -> customers", "status project_status NOT NULL", "FK created_by uuid NOT NULL -> users", "row_version bigint NOT NULL DEFAULT 1", "created_at timestamptz NOT NULL", "updated_at timestamptz NOT NULL"),
            T("project_development_levels", "iam", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "level_code varchar(40) NOT NULL", "name varchar(120) NOT NULL", "sort_order smallint NOT NULL", "active boolean NOT NULL DEFAULT true", "row_version bigint NOT NULL DEFAULT 1", "UQ (project_id,level_code)"),
            T("project_assignments", "iam", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK user_id uuid NOT NULL -> users", "FK assigned_by uuid NOT NULL -> users", "assigned_at timestamptz NOT NULL", "FK unassigned_by uuid NULL -> users", "unassigned_at timestamptz NULL", "unassignment_reason text NULL", "UQ partial (project_id,user_id) WHERE unassigned_at IS NULL", "CK unassigned_at>assigned_at when set; immutable history"),
            T("reference_list_types", "iam", "PK id smallint", "UQ code varchar(40) NOT NULL", "name varchar(100) NOT NULL", "scope reference_scope NOT NULL", "active boolean NOT NULL DEFAULT true"),
            T("reference_list_items", "iam", "PK id uuid", "FK type_id smallint NOT NULL -> reference_list_types", "FK project_id uuid NULL -> projects", "code varchar(80) NULL", "label varchar(150) NOT NULL", "active boolean NOT NULL DEFAULT true", "FK created_by uuid NOT NULL -> users", "row_version bigint NOT NULL DEFAULT 1", "created_at timestamptz NOT NULL", "deactivated_at timestamptz NULL", "UQ NULLS NOT DISTINCT (type_id,project_id,code)", "CK non-authoritative extension values only"),
            T("fgpns", "iam", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "fgpn_code varchar(32) NOT NULL", "description varchar(50) NULL", "active boolean NOT NULL DEFAULT true", "row_version bigint NOT NULL DEFAULT 1", "UQ (project_id,fgpn_code)", "CK format validated by approved project rule"),
            T("document_encryption_keys", "iam", "PK id uuid", "provider varchar(40) NOT NULL", "kms_key_ref varchar(255) NOT NULL", "key_version varchar(80) NOT NULL", "algorithm varchar(40) NOT NULL", "status key_status NOT NULL", "activated_at timestamptz NOT NULL", "retired_at timestamptz NULL", "UQ (kms_key_ref,key_version)", "CK external KMS reference only; never key material"),
            T("documents", "iam", "PK id uuid", "document_type document_type NOT NULL", "file_name varchar(255) NOT NULL", "mime_type varchar(100) NOT NULL", "byte_size bigint NOT NULL", "UQ storage_key text NOT NULL", "checksum_sha256 bytea NOT NULL", "FK encryption_key_id uuid NOT NULL -> document_encryption_keys", "retention_class varchar(60) NOT NULL", "retain_until timestamptz NULL", "legal_hold boolean NOT NULL DEFAULT false", "status document_status NOT NULL", "FK uploaded_by uuid NULL -> users", "uploaded_at timestamptz NOT NULL", "CK byte_size>0; purge blocked by hold/retention", "IX checksum_sha256"),
            T("document_signatures", "iam", "PK id uuid", "FK document_id uuid NOT NULL -> documents", "FK manufacturing_receiver_id uuid NULL -> manufacturing_receivers", "FK signer_user_id uuid NULL -> users", "signer_name_snapshot varchar(150) NOT NULL", "signature_role varchar(80) NOT NULL", "FK uploaded_by uuid NOT NULL -> users", "signed_at timestamptz NULL", "recorded_at timestamptz NOT NULL", "UQ (document_id,signature_role,signer_name_snapshot)", "CK exactly one typed signer identity when known"),
            T("system_settings", "cross", "PK setting_key varchar(100)", "setting_value jsonb NOT NULL", "value_schema_version integer NOT NULL", "FK updated_by uuid NOT NULL -> users", "updated_at timestamptz NOT NULL", "row_version bigint NOT NULL DEFAULT 1"),
        ],
        relations=[
            Rel("roles", "role_permissions"), Rel("permissions", "role_permissions"), Rel("roles", "user_role_assignments"),
            Rel("users", "user_role_assignments", "1 user to 1 active + history"), Rel("roles", "users", "checked current-role cache", True),
            Rel("users", "user_sessions"), Rel("users", "login_events", "1 to 0..*; failed may be anonymous"),
            Rel("customers", "customer_contacts"), Rel("customers", "projects"), Rel("users", "manufacturing_receivers", "0..1 account to 0..1 receiver"),
            Rel("projects", "project_development_levels"), Rel("users", "project_assignments"), Rel("projects", "project_assignments"),
            Rel("reference_list_types", "reference_list_items"), Rel("projects", "reference_list_items", "0..1 project scope to 0..*"),
            Rel("projects", "fgpns"), Rel("users", "documents", "0..1 uploader to 0..*"),
            Rel("document_encryption_keys", "documents"), Rel("documents", "document_signatures"),
            Rel("manufacturing_receivers", "document_signatures", "0..1 receiver to 0..* signatures"), Rel("users", "system_settings"),
        ],
        notes=[
            N("Session and lock invariant", "A revoked, expired, inactive, or 60-minutes-idle session cannot authorize a request. Password lock occurs after 5 consecutive failures. Every mutable aggregate save includes WHERE row_version = :loaded_version and increments the version; zero updated rows means reload."),
            N("Role and project-scope invariant", "user_role_assignments preserves every grant/revocation; a partial unique index permits at most one open role row and a deferred trigger requires exactly one for every active user. users.current_role_id is only a checked cache of that row. project_assignments grants project visibility independently and temporally; it carries no second role that could disagree."),
            N("Typed reference integrity", "Customers, contacts, manufacturing receivers, delivery methods, material types, development levels, and FGPNs are authoritative typed masters. reference_list_items remains only for non-authoritative extensions; no core business FK may point to it. Inactive master rows remain readable historically."),
            N("Document invariant", "File bytes are immutable in encrypted object storage; a replacement is a new documents row. Only an external KMS key reference/version is stored. Retention class, retain-until, and legal hold gate purge. Signed documents retain typed signer identity, signer snapshot, uploader, checksum, and content-sniffing evidence."),
        ],
    ))

    pages.append(Page(
        "03 PO Intake/Stable Items/Immutable Versions/Status",
        "All 20 extraction fields, stable line identity across versions, reproducible comparisons, and governed status history.",
        nodes=[
            T("po_uploads", "po", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK document_id uuid NOT NULL -> documents", "FK uploaded_by uuid NOT NULL -> users", "uploaded_at timestamptz NOT NULL", "status po_upload_status NOT NULL", "rejection_reason text NULL", "UQ document_id", "CK document is PDF; stored even if rejected"),
            T("po_extraction_runs", "po", "PK id uuid", "FK po_upload_id uuid NOT NULL -> po_uploads", "attempt_no smallint NOT NULL", "parser_name varchar(80) NOT NULL", "parser_version varchar(40) NOT NULL", "status extraction_status NOT NULL", "started_at timestamptz NOT NULL", "completed_at timestamptz NULL", "error_message text NULL", "UQ (po_upload_id,attempt_no)"),
            T("po_extracted_values", "po", "PK id uuid", "FK extraction_run_id uuid NOT NULL -> po_extraction_runs", "line_ordinal integer NOT NULL DEFAULT 0", "field_key po_field_key NOT NULL", "raw_text text NULL", "extracted_value text NULL", "corrected_value text NULL", "final_value text NULL", "validation_status validation_status NOT NULL", "validation_message text NULL", "expected_value text NULL", "FK corrected_by uuid NULL -> users", "corrected_at timestamptz NULL", "UQ (extraction_run_id,line_ordinal,field_key)", "CK line_ordinal=0 header; >0 line"),
            T("purchase_orders", "po", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "po_number char(10) NOT NULL", "FK current_version_id uuid NULL -> purchase_order_versions", "current_status po_status NOT NULL", "FK created_by uuid NOT NULL -> users", "created_at timestamptz NOT NULL", "row_version bigint NOT NULL DEFAULT 1", "UQ (project_id,po_number)", "CK length(po_number)=10"),
            T("purchase_order_items", "po", "PK id uuid", "FK purchase_order_id uuid NOT NULL -> purchase_orders", "UQ stable_item_key uuid NOT NULL", "external_item_key varchar(80) NULL", "created_at timestamptz NOT NULL", "retired_at timestamptz NULL", "IX (purchase_order_id,external_item_key)"),
            T("purchase_order_versions", "po", "PK id uuid", "FK purchase_order_id uuid NOT NULL -> purchase_orders", "FK po_upload_id uuid NOT NULL -> po_uploads", "version_no integer NOT NULL", "FK customer_id uuid NOT NULL -> customers", "FK customer_contact_id uuid NOT NULL -> customer_contacts", "customer_code_snapshot varchar(40) NOT NULL", "customer_name_snapshot varchar(180) NOT NULL", "contact_name_snapshot varchar(150) NOT NULL", "contact_details_snapshot jsonb NOT NULL", "document_date date NOT NULL", "reason_of_po text NOT NULL", "car_model varchar(80) NULL", "FK confirmed_by uuid NOT NULL -> users", "confirmed_at timestamptz NOT NULL", "content_hash bytea NOT NULL", "UQ (purchase_order_id,version_no)", "UQ (purchase_order_id,content_hash)", "CK contact belongs customer; customer matches project", "CK immutable: no UPDATE/DELETE"),
            T("purchase_order_version_items", "po", "PK id uuid", "FK po_version_id uuid NOT NULL -> purchase_order_versions", "FK po_item_id uuid NOT NULL -> purchase_order_items", "line_number integer NOT NULL", "item varchar(80) NOT NULL", "part_number char(7) NULL", "FK fgpn_id uuid NOT NULL -> fgpns", "fgpn_code_snapshot varchar(32) NOT NULL", "FK development_level_id uuid NOT NULL -> project_development_levels", "development_level_code_snapshot varchar(40) NOT NULL", "engineering_phase_level varchar(40) NULL", "color_code char(4) NULL", "description varchar(50) NULL", "trim_code varchar(40) NULL", "po_level varchar(6) NULL", "quantity numeric(20,4) NOT NULL", "unit_price numeric(20,4) NOT NULL", "delivery_date date NOT NULL", "pickup_date date NULL", "row_hash bytea NOT NULL", "UQ (po_version_id,po_item_id)", "UQ (po_version_id,line_number)", "CK FGPN/development level belong to PO project", "CK quantity>0 AND unit_price>=0; immutable"),
            T("po_version_comparisons", "po", "PK id uuid", "FK purchase_order_id uuid NOT NULL -> purchase_orders", "FK version_a_id uuid NOT NULL -> purchase_order_versions", "FK version_b_id uuid NOT NULL -> purchase_order_versions", "FK compared_by uuid NOT NULL -> users", "compared_at timestamptz NOT NULL", "UQ (version_a_id,version_b_id)", "CK versions differ and belong to same PO"),
            T("po_version_comparison_items", "po", "PK id uuid", "FK comparison_id uuid NOT NULL -> po_version_comparisons", "FK po_item_id uuid NULL -> purchase_order_items", "scope comparison_scope NOT NULL", "field_key po_field_key NOT NULL", "value_a text NULL", "value_b text NULL", "change_type change_type NOT NULL", "UQ NULLS NOT DISTINCT (comparison_id,po_item_id,scope,field_key)"),
            T("po_allowed_status_transitions", "po", "PK id smallint", "from_status po_status NOT NULL", "to_status po_status NOT NULL", "direction transition_direction NOT NULL", "requires_reason boolean NOT NULL", "active boolean NOT NULL DEFAULT true", "UQ (from_status,to_status)"),
            T("po_status_transition_roles", "po", "FK transition_id smallint NOT NULL -> po_allowed_status_transitions", "FK role_id smallint NOT NULL -> roles", "PK (transition_id,role_id)"),
            T("po_status_history", "po", "PK id uuid", "FK purchase_order_id uuid NOT NULL -> purchase_orders", "sequence_no bigint NOT NULL", "from_status po_status NULL", "to_status po_status NOT NULL", "FK transition_id smallint NOT NULL -> po_allowed_status_transitions", "reason text NULL", "FK changed_by uuid NOT NULL -> users", "changed_at timestamptz NOT NULL", "UQ (purchase_order_id,sequence_no)", "CK reason required per transition", "CK immutable: no UPDATE/DELETE"),
            T("production_events", "po", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK launch_operation_id uuid NOT NULL -> launch_operations", "UQ idempotency_key uuid NOT NULL", "source_system varchar(40) NOT NULL", "source_event_key varchar(120) NOT NULL", "payload_hash bytea NOT NULL", "FK evidence_document_id uuid NULL -> documents", "FK recorded_by uuid NOT NULL -> users", "occurred_at timestamptz NOT NULL", "recorded_at timestamptz NOT NULL", "UQ (source_system,source_event_key)", "CK immutable; key reuse requires same payload hash"),
            T("production_event_items", "po", "PK id uuid", "FK production_event_id uuid NOT NULL -> production_events", "FK po_item_id uuid NOT NULL -> purchase_order_items", "line_no integer NOT NULL", "quantity_produced numeric(20,4) NOT NULL", "UQ (production_event_id,line_no)", "UQ (production_event_id,po_item_id)", "CK quantity_produced>0; immutable partial-production fact"),
            V("v_po_item_balance", "po", "po_item_id uuid", "ordered_qty from current immutable PO version", "launched_qty from launch_operation_items", "produced_qty from production_event_items", "in_manufacturing_qty = launched-produced", "confirmed_delivered_qty from confirmed customer_delivery_lines", "remaining_to_launch / remaining_to_deliver", "amount_remaining and ISO weeks generated at query"),
        ],
        relations=[
            Rel("po_uploads", "po_extraction_runs"), Rel("po_extraction_runs", "po_extracted_values"),
            Rel("purchase_orders", "purchase_order_items"), Rel("purchase_orders", "purchase_order_versions"),
            Rel("po_uploads", "purchase_order_versions", "1 upload to 0..1 confirmed version"),
            Rel("purchase_order_versions", "purchase_order_version_items"), Rel("purchase_order_items", "purchase_order_version_items"),
            Rel("purchase_orders", "po_version_comparisons"), Rel("po_version_comparisons", "po_version_comparison_items"),
            Rel("purchase_order_items", "po_version_comparison_items", "0..1 item to 0..* diffs"),
            Rel("po_allowed_status_transitions", "po_status_transition_roles"), Rel("purchase_orders", "po_status_history"),
            Rel("po_allowed_status_transitions", "po_status_history"), Rel("production_events", "production_event_items"),
            Rel("purchase_order_items", "production_event_items"), Rel("purchase_order_items", "v_po_item_balance", "typed-fact projection", True),
        ],
        notes=[
            N("20-field extraction coverage", "po_field_key contains: jit_customer, contact_information, document_date, delivery_date, item, fgpn, development_level, quantity, unit_price, reason_of_po, po_number, delivery_week, car_model, engineering_phase_level, color_code, description, trim_code, po_level, pickup_date, pickup_week. Derived weeks are still stored as reviewed extraction values; authoritative weeks are generated from dates."),
            N("Stable item invariant", "A version row never becomes the identity used by deliveries or launch operations. purchase_order_items is the durable identity; every version maps its lines to that identity. Added lines get new stable items, removed lines simply do not appear in the later immutable snapshot, and ambiguous matching requires user confirmation."),
            N("Version/status invariant", "Versions and their item rows are append-only and copy customer, contact, FGPN, and development-level display values so history survives master-data edits. purchase_orders.current_version_id/current_status are checked caches. Each from/to transition is unique; any number of allowed roles is attached through po_status_transition_roles."),
            N("Typed progress invariant", "There is no polymorphic progress table. Launched quantity comes only from launch_operation_items, partial produced quantity from append-only production_event_items, and delivered quantity only from confirmed customer_delivery_lines. v_po_item_balance joins those typed stable-PO-item facts; deferred checks prevent produced>launched or delivered>produced."),
        ],
    ))

    # Remaining pages are appended below. Keeping definitions in one generator
    # makes the artifact reproducible and reviewable as source code.
    pages.extend(_build_operational_pages())
    return pages


def _build_operational_pages() -> list[Page]:
    """Pages 04-07; split only to keep build_pages readable."""
    pages: list[Page] = []

    pages.append(Page(
        "04 BOM/Simulation/Launch",
        "Complete xlsx BOM snapshots, reproducible multi-PO/future-stock simulations, and meeting-gated launch decisions.",
        nodes=[
            T("materials", "bom", "PK id uuid", "UQ material_part_number varchar(10) NOT NULL", "description varchar(50) NOT NULL", "FK material_type_id uuid NOT NULL -> material_types", "status material_status NOT NULL", "base_uom varchar(12) NOT NULL", "row_version bigint NOT NULL DEFAULT 1", "IX pg_trgm GIN (material_part_number gin_trgm_ops, description gin_trgm_ops)"),
            T("bom_imports", "bom", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK source_document_id uuid NOT NULL -> documents", "source_format varchar(8) NOT NULL", "template_version varchar(30) NOT NULL", "file_hash bytea NOT NULL", "FK imported_by uuid NOT NULL -> users", "imported_at timestamptz NOT NULL", "status bom_import_status NOT NULL", "error_summary text NULL", "UQ (project_id,file_hash)", "CK source_format='xlsx'"),
            T("bom_import_rows", "bom", "PK id uuid", "FK bom_import_id uuid NOT NULL -> bom_imports", "sheet_name varchar(80) NOT NULL", "row_number integer NOT NULL", "raw_values jsonb NOT NULL", "normalized_values jsonb NULL", "validation_errors jsonb NOT NULL DEFAULT '[]'", "UQ (bom_import_id,sheet_name,row_number)"),
            T("bom_revisions", "bom", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK created_from_import_id uuid NOT NULL -> bom_imports", "revision_no integer NOT NULL", "source_revision_code varchar(40) NULL", "status bom_status NOT NULL", "snapshot_hash bytea NOT NULL", "FK confirmed_by uuid NULL -> users", "confirmed_at timestamptz NULL", "created_at timestamptz NOT NULL", "activated_at timestamptz NULL", "replaced_at timestamptz NULL", "UQ (project_id,revision_no)", "UQ (project_id,snapshot_hash)", "UQ partial project_id WHERE status='active'", "CK confirmed_by/at together; active requires confirmation", "CK immutable after validation"),
            T("bom_revision_items", "bom", "PK id uuid", "FK bom_revision_id uuid NOT NULL -> bom_revisions", "FK fgpn_id uuid NOT NULL -> fgpns", "component_key varchar(80) NOT NULL", "FK material_id uuid NOT NULL -> materials", "usage_quantity numeric(20,4) NOT NULL", "uom varchar(12) NOT NULL", "source_row integer NOT NULL", "row_hash bytea NOT NULL", "UQ (bom_revision_id,fgpn_id,component_key)", "CK usage_quantity>0", "CK full immutable snapshot row"),
            T("bom_version_comparisons", "bom", "PK id uuid", "FK old_revision_id uuid NOT NULL -> bom_revisions", "FK new_revision_id uuid NOT NULL -> bom_revisions", "FK compared_by uuid NOT NULL -> users", "compared_at timestamptz NOT NULL", "UQ (old_revision_id,new_revision_id)", "CK same project and revisions differ"),
            T("bom_version_comparison_items", "bom", "PK id uuid", "FK comparison_id uuid NOT NULL -> bom_version_comparisons", "FK fgpn_id uuid NOT NULL -> fgpns", "FK material_id uuid NOT NULL -> materials", "component_key varchar(80) NOT NULL", "old_usage numeric(20,4) NULL", "new_usage numeric(20,4) NULL", "change_type change_type NOT NULL", "UQ (comparison_id,fgpn_id,component_key)"),
            T("simulation_policies", "bom", "PK id uuid", "FK project_id uuid NULL -> projects", "name varchar(100) NOT NULL", "active boolean NOT NULL DEFAULT true", "FK created_by uuid NOT NULL -> users", "created_at timestamptz NOT NULL", "row_version bigint NOT NULL DEFAULT 1", "UQ NULLS NOT DISTINCT (project_id,name)"),
            T("simulation_policy_versions", "bom", "PK id uuid", "FK policy_id uuid NOT NULL -> simulation_policies", "version_no integer NOT NULL", "safety_coefficient numeric(12,4) NOT NULL", "priority_rule varchar(60) NOT NULL", "tie_break_rule varchar(60) NOT NULL", "stock_pool_rules jsonb NOT NULL", "future_stock_rules jsonb NOT NULL", "effective_from timestamptz NOT NULL", "FK created_by uuid NOT NULL -> users", "created_at timestamptz NOT NULL", "UQ (policy_id,version_no)", "CK safety_coefficient>0; immutable"),
            T("launch_simulations", "bom", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "simulation_type simulation_type NOT NULL", "FK policy_version_id uuid NOT NULL -> simulation_policy_versions", "policy_snapshot jsonb NOT NULL", "as_of_at timestamptz NOT NULL", "FK run_by uuid NOT NULL -> users", "run_at timestamptz NOT NULL", "result_status simulation_result NOT NULL", "FK draft_document_id uuid NULL -> documents", "input_hash bytea NOT NULL", "UQ (project_id,input_hash,run_at)", "CK immutable after completion"),
            T("simulation_purchase_orders", "bom", "PK id uuid", "FK simulation_id uuid NOT NULL -> launch_simulations", "FK purchase_order_id uuid NOT NULL -> purchase_orders", "FK po_version_id uuid NOT NULL -> purchase_order_versions", "priority_rank integer NOT NULL", "delivery_date_snapshot date NULL", "po_value_snapshot numeric(20,4) NULL", "UQ (simulation_id,purchase_order_id)", "UQ (simulation_id,priority_rank)", "CK exact immutable PO version"),
            T("simulation_item_results", "bom", "PK id uuid", "FK simulation_po_id uuid NOT NULL -> simulation_purchase_orders", "FK po_item_id uuid NOT NULL -> purchase_order_items", "FK po_version_item_id uuid NOT NULL -> purchase_order_version_items", "FK bom_revision_id uuid NOT NULL -> bom_revisions", "requested_qty numeric(20,4) NOT NULL", "already_launched_qty_snapshot numeric(20,4) NOT NULL", "already_in_manufacturing_qty_snapshot numeric(20,4) NOT NULL", "GEN remaining_to_launch_qty numeric(20,4)", "launchable_qty numeric(20,4) NOT NULL", "result simulation_item_result NOT NULL", "UQ (simulation_po_id,po_item_id)", "CK nonnegative; in_manufacturing<=launched<=requested", "CK remaining=greatest(requested-launched,0)", "CK launchable<=remaining_to_launch_qty"),
            T("simulation_stock_inputs", "bom", "PK id uuid", "FK simulation_id uuid NOT NULL -> launch_simulations", "FK material_id uuid NOT NULL -> materials", "warehouse_qty_snapshot numeric(20,4) NOT NULL", "wip_qty_snapshot numeric(20,4) NOT NULL", "transit_qty_snapshot numeric(20,4) NOT NULL", "planned_qty_snapshot numeric(20,4) NOT NULL", "usable_qty_snapshot numeric(20,4) NOT NULL", "pool_breakdown_snapshot jsonb NOT NULL", "balance_as_of timestamptz NOT NULL", "UQ (simulation_id,material_id)", "CK component snapshots and usable_qty are nonnegative"),
            T("simulation_future_arrival_inputs", "bom", "PK id uuid", "FK simulation_id uuid NOT NULL -> launch_simulations", "FK material_id uuid NOT NULL -> materials", "FK future_arrival_id uuid NOT NULL -> future_stock_arrivals", "quantity_snapshot numeric(20,4) NOT NULL", "expected_arrival_date_snapshot date NOT NULL", "UQ (simulation_id,future_arrival_id)", "CK immutable selected arrival; quantity>0"),
            T("simulation_material_allocations", "bom", "PK id uuid", "FK simulation_item_result_id uuid NOT NULL -> simulation_item_results", "FK material_id uuid NOT NULL -> materials", "usage_snapshot numeric(20,4) NOT NULL", "safety_coefficient_snapshot numeric(12,4) NOT NULL", "required_qty numeric(20,4) NOT NULL", "allocated_qty numeric(20,4) NOT NULL", "shortfall_qty numeric(20,4) NOT NULL", "UQ (simulation_item_result_id,material_id)", "CK required=usage*safety*remaining_to_launch", "CK shortfall=greatest(required-allocated,0)"),
            T("launch_operations", "bom", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK simulation_id uuid NOT NULL -> launch_simulations", "status launch_operation_status NOT NULL", "FK meeting_minutes_document_id uuid NULL -> documents", "FK approved_by uuid NULL -> users", "approved_at timestamptz NULL", "finalized_at timestamptz NULL", "row_version bigint NOT NULL DEFAULT 1", "UQ simulation_id", "CK finalized => meeting minutes + approval"),
            T("launch_operation_items", "bom", "PK id uuid", "FK launch_operation_id uuid NOT NULL -> launch_operations", "FK simulation_item_result_id uuid NOT NULL -> simulation_item_results", "FK po_item_id uuid NOT NULL -> purchase_order_items", "FK bom_revision_id uuid NOT NULL -> bom_revisions", "quantity_launched numeric(20,4) NOT NULL", "UQ (launch_operation_id,po_item_id)", "CK quantity_launched>0 and <= simulated launchable"),
            T("bom_impact_reviews", "bom", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK launch_operation_id uuid NULL -> launch_operations", "FK old_revision_id uuid NOT NULL -> bom_revisions", "FK new_revision_id uuid NOT NULL -> bom_revisions", "status impact_review_status NOT NULL", "created_at timestamptz NOT NULL", "FK reviewed_by uuid NULL -> users", "reviewed_at timestamptz NULL", "UQ (launch_operation_id,old_revision_id,new_revision_id)"),
            T("bom_impact_review_items", "bom", "PK id uuid", "FK review_id uuid NOT NULL -> bom_impact_reviews", "FK material_id uuid NOT NULL -> materials", "old_required_qty numeric(20,4) NOT NULL", "new_required_qty numeric(20,4) NOT NULL", "difference_qty numeric(20,4) NOT NULL", "UQ (review_id,material_id)", "CK difference=new-old"),
            V("v_simulation_shortfalls", "bom", "simulation_id uuid", "material_id uuid", "required / allocated / shortfall numeric(20,4)", "project + PO + priority context", "export source for missing-material document"),
            V("v_launch_readiness", "bom", "launch_operation_id uuid", "policy/BOM/PO snapshot references", "meeting_minutes_present boolean", "approved boolean", "ready_to_finalize boolean"),
        ],
        relations=[
            Rel("bom_imports", "bom_import_rows"), Rel("bom_imports", "bom_revisions", "1 import to 0..1 accepted revision"),
            Rel("bom_revisions", "bom_revision_items"), Rel("materials", "bom_revision_items"),
            Rel("bom_revisions", "bom_version_comparisons", "revision participates in comparisons"),
            Rel("bom_version_comparisons", "bom_version_comparison_items"), Rel("materials", "bom_version_comparison_items"),
            Rel("simulation_policies", "simulation_policy_versions"), Rel("simulation_policy_versions", "launch_simulations"),
            Rel("launch_simulations", "simulation_purchase_orders"), Rel("simulation_purchase_orders", "simulation_item_results"),
            Rel("bom_revisions", "simulation_item_results"), Rel("launch_simulations", "simulation_stock_inputs"),
            Rel("materials", "simulation_stock_inputs"), Rel("launch_simulations", "simulation_future_arrival_inputs"),
            Rel("materials", "simulation_future_arrival_inputs"), Rel("simulation_item_results", "simulation_material_allocations"),
            Rel("materials", "simulation_material_allocations"), Rel("launch_simulations", "launch_operations", "1 completed simulation to 0..1 launch"),
            Rel("launch_operations", "launch_operation_items"), Rel("simulation_item_results", "launch_operation_items"),
            Rel("bom_revisions", "bom_impact_reviews", "old/new revisions"), Rel("bom_impact_reviews", "bom_impact_review_items"),
            Rel("simulation_material_allocations", "v_simulation_shortfalls", "facts to projection", True),
            Rel("launch_operations", "v_launch_readiness", "1 to 1 projection", True),
        ],
        notes=[
            N("Full-snapshot BOM", "Each accepted xlsx upload creates one project-level bom_revisions row and the complete set of bom_revision_items for all FGPN/material components. No valid-from/valid-to component deltas are used. Exactly one active revision per project is enforced by a partial unique index; replacing it never deletes the old snapshot."),
            N("Reproducible simulation", "Each PO item snapshots requested, already launched, and already in-manufacturing quantities. Each material snapshots warehouse, WIP, transit, planned, policy-usable totals, and the pool breakdown. Every selected future arrival is a separate immutable row with quantity/date. Together with exact PO/BOM/policy versions, the same input hash reproduces the result."),
            N("Meeting-minutes gate", "A deferred trigger blocks finalized launch_operations unless meeting_minutes_document_id is a valid stored PDF and approval exists. Warehouse instructions additionally require a finalized/approved operation. Future-stock simulations never post inventory; their clearly marked draft document is retained."),
        ],
    ))

    pages.append(Page(
        "05 Inventory Ledger/Warehouse Transfer",
        "Stock pools/locations, immutable exact-once ledger postings, future arrivals, and signed warehouse-to-manufacturing transfer.",
        nodes=[
            T("inventory_locations", "inventory", "PK id uuid", "UQ location_code varchar(30) NOT NULL", "name varchar(120) NOT NULL", "location_type location_type NOT NULL", "FK project_id uuid NULL -> projects", "active boolean NOT NULL DEFAULT true", "row_version bigint NOT NULL DEFAULT 1"),
            T("stock_pools", "inventory", "PK id uuid", "UQ pool_code varchar(30) NOT NULL", "name varchar(120) NOT NULL", "pool_type stock_pool_type NOT NULL", "scope_mode stock_pool_scope NOT NULL", "included_in_practical boolean NOT NULL", "included_in_theoretical boolean NOT NULL", "included_in_standard_sim boolean NOT NULL", "active boolean NOT NULL DEFAULT true"),
            T("project_stock_pools", "inventory", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK stock_pool_id uuid NOT NULL -> stock_pools", "effective_from timestamptz NOT NULL", "effective_to timestamptz NULL", "FK mapped_by uuid NOT NULL -> users", "UQ (project_id,stock_pool_id,effective_from)", "UQ partial (project_id,stock_pool_id) WHERE effective_to IS NULL", "EXCLUDE overlapping membership per project/pool", "CK project-scoped pool has one project; shared pool may map many"),
            T("stock_pool_locations", "inventory", "PK id uuid", "FK stock_pool_id uuid NOT NULL -> stock_pools", "FK location_id uuid NOT NULL -> inventory_locations", "effective_from timestamptz NOT NULL", "effective_to timestamptz NULL", "UQ (stock_pool_id,location_id,effective_from)", "CK effective_to>effective_from when set", "EXCLUDE overlapping membership per location"),
            T("inventory_events", "inventory", "PK id uuid", "event_type inventory_event_type NOT NULL", "source_system varchar(40) NOT NULL", "source_event_key varchar(120) NOT NULL", "UQ idempotency_key uuid NOT NULL", "payload_hash bytea NOT NULL", "occurred_at timestamptz NOT NULL", "FK created_by uuid NULL -> users", "created_at timestamptz NOT NULL", "posted_at timestamptz NOT NULL", "FK reversal_of_event_id uuid NULL -> inventory_events", "UQ (source_system,source_event_key)", "UQ reversal_of_event_id", "CK immutable; payload key reuse must match hash"),
            T("inventory_postings", "inventory", "PK id uuid", "FK event_id uuid NOT NULL -> inventory_events", "line_no integer NOT NULL", "FK project_id uuid NULL -> projects", "FK material_id uuid NOT NULL -> materials", "FK location_id uuid NOT NULL -> inventory_locations", "quantity_delta numeric(20,4) NOT NULL", "uom varchar(12) NOT NULL", "lot_reference varchar(80) NULL", "UQ (event_id,line_no)", "CK quantity_delta<>0; immutable"),
            T("stock_receptions", "inventory", "PK id uuid", "FK project_id uuid NULL -> projects", "FK receiving_location_id uuid NOT NULL -> inventory_locations", "supplier_reference varchar(100) NULL", "FK received_by uuid NOT NULL -> users", "received_at timestamptz NOT NULL", "correction_deadline timestamptz NOT NULL", "row_version bigint NOT NULL DEFAULT 1", "CK deadline=received_at+24h"),
            T("stock_reception_lines", "inventory", "PK id uuid", "FK reception_id uuid NOT NULL -> stock_receptions", "line_no integer NOT NULL", "FK material_id uuid NOT NULL -> materials", "quantity_received numeric(20,4) NOT NULL", "FK inventory_event_id uuid NOT NULL -> inventory_events", "UQ (reception_id,line_no)", "UQ inventory_event_id", "CK quantity_received>0"),
            T("stock_reception_corrections", "inventory", "PK id uuid", "FK reception_line_id uuid NOT NULL -> stock_reception_lines", "previous_quantity numeric(20,4) NOT NULL", "corrected_quantity numeric(20,4) NOT NULL", "reason text NOT NULL", "FK corrected_by uuid NOT NULL -> users", "corrected_at timestamptz NOT NULL", "FK reversal_event_id uuid NOT NULL -> inventory_events", "FK replacement_event_id uuid NOT NULL -> inventory_events", "UQ reversal_event_id", "UQ replacement_event_id", "CK immutable; original line not updated"),
            T("cutman_imports", "inventory", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK stock_pool_id uuid NOT NULL -> stock_pools", "FK document_id uuid NOT NULL -> documents", "import_format cutman_format NOT NULL", "file_hash bytea NOT NULL", "FK imported_by uuid NOT NULL -> users", "imported_at timestamptz NOT NULL", "status import_status NOT NULL", "error_message text NULL", "UQ (project_id,stock_pool_id,file_hash)", "CK active project_stock_pools mapping required", "CK format IN ('xlsx','sql_data')"),
            T("cutman_import_lines", "inventory", "PK id uuid", "FK cutman_import_id uuid NOT NULL -> cutman_imports", "row_number integer NOT NULL", "FK material_id uuid NOT NULL -> materials", "FK wip_location_id uuid NOT NULL -> inventory_locations", "reported_wip_qty numeric(20,4) NOT NULL", "prior_qty_snapshot numeric(20,4) NOT NULL", "delta_posted numeric(20,4) NOT NULL", "FK inventory_event_id uuid NOT NULL -> inventory_events", "UQ (cutman_import_id,row_number)", "UQ inventory_event_id"),
            T("future_stock_arrivals", "inventory", "PK id uuid", "FK project_id uuid NULL -> projects", "FK material_id uuid NOT NULL -> materials", "FK destination_location_id uuid NOT NULL -> inventory_locations", "source_reference varchar(100) NULL", "quantity_expected numeric(20,4) NOT NULL", "expected_arrival_date date NOT NULL", "status arrival_status NOT NULL", "FK entered_by uuid NOT NULL -> users", "entered_at timestamptz NOT NULL", "FK receipt_event_id uuid NULL -> inventory_events", "row_version bigint NOT NULL DEFAULT 1", "CK quantity_expected>0", "UQ receipt_event_id"),
            T("stock_thresholds", "inventory", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK material_id uuid NOT NULL -> materials", "threshold_qty numeric(20,4) NOT NULL", "valid_during tstzrange NOT NULL", "FK defined_by uuid NOT NULL -> users", "created_at timestamptz NOT NULL", "CK threshold_qty>=0", "EXCLUDE overlap (project_id,material_id,valid_during)"),
            T("warehouse_delivery_instructions", "delivery", "PK id uuid", "FK launch_operation_id uuid NOT NULL -> launch_operations", "FK project_id uuid NOT NULL -> projects", "required_at timestamptz NOT NULL", "status warehouse_instruction_status NOT NULL", "FK created_by uuid NOT NULL -> users", "created_at timestamptz NOT NULL", "row_version bigint NOT NULL DEFAULT 1", "UQ launch_operation_id", "CK launch finalized and meeting minutes present"),
            T("warehouse_delivery_instruction_lines", "delivery", "PK id uuid", "FK instruction_id uuid NOT NULL -> warehouse_delivery_instructions", "line_no integer NOT NULL", "FK material_id uuid NOT NULL -> materials", "description_snapshot varchar(50) NOT NULL", "quantity_to_deliver numeric(20,4) NOT NULL", "uom varchar(12) NOT NULL", "UQ (instruction_id,line_no)", "UQ (instruction_id,material_id)", "CK quantity_to_deliver>0"),
            T("delivery_codes", "delivery", "PK id uuid", "FK instruction_id uuid NOT NULL -> warehouse_delivery_instructions", "UQ code_digest bytea NOT NULL", "FK generated_by uuid NOT NULL -> users", "generated_at timestamptz NOT NULL", "expires_at timestamptz NOT NULL", "consumed_at timestamptz NULL", "FK consumed_by uuid NULL -> users", "revoked_at timestamptz NULL", "CK expires_at>generated_at", "CK consumed once; digest only", "UQ partial one unconsumed code per instruction"),
            T("delivery_code_access_events", "delivery", "PK id bigint GENERATED IDENTITY", "FK delivery_code_id uuid NULL -> delivery_codes", "entered_code_digest bytea NOT NULL", "FK entered_by uuid NULL -> users", "entered_at timestamptz NOT NULL", "success boolean NOT NULL", "failure_reason varchar(80) NULL", "ip_address inet NULL", "CK immutable"),
            T("warehouse_delivery_documents", "delivery", "PK id uuid", "FK instruction_id uuid NOT NULL -> warehouse_delivery_instructions", "FK document_id uuid NOT NULL -> documents", "FK warehouse_leader_id uuid NOT NULL -> users", "FK manufacturing_receiver_id uuid NOT NULL -> manufacturing_receivers", "receiver_name_snapshot varchar(150) NOT NULL", "generated_at timestamptz NOT NULL", "UQ instruction_id", "UQ document_id"),
            T("warehouse_delivery_receipts", "delivery", "PK id uuid", "FK warehouse_document_id uuid NOT NULL -> warehouse_delivery_documents", "FK signed_document_id uuid NOT NULL -> documents", "FK document_signature_id uuid NOT NULL -> document_signatures", "status signed_document_status NOT NULL", "FK uploaded_by uuid NOT NULL -> users", "uploaded_at timestamptz NOT NULL", "FK validated_by uuid NULL -> users", "validated_at timestamptz NULL", "FK inventory_event_id uuid NULL -> inventory_events", "row_version bigint NOT NULL DEFAULT 1", "UQ signed_document_id", "UQ document_signature_id", "UQ inventory_event_id", "UQ partial warehouse_document_id WHERE status='validated'", "UQ partial warehouse_document_id WHERE inventory_event_id IS NOT NULL", "CK validator/time may record rejection; event only when validated"),
            V("v_inventory_balance", "inventory", "project_id / material_id / location_id", "on_hand_qty = SUM(inventory_postings.quantity_delta)", "as_of latest posted event", "refresh transactionally or incrementally"),
            V("v_stock_summary", "inventory", "project_id / material_id", "practical_stock from practical pools", "wip_stock from WIP pools", "theoretical_stock = practical + open arrivals", "standard_sim_available = warehouse + usable WIP", "threshold state derived"),
        ],
        relations=[
            Rel("stock_pools", "project_stock_pools"), Rel("stock_pools", "stock_pool_locations"), Rel("inventory_locations", "stock_pool_locations"),
            Rel("inventory_events", "inventory_postings"), Rel("inventory_locations", "inventory_postings"),
            Rel("stock_receptions", "stock_reception_lines"), Rel("inventory_events", "stock_reception_lines", "1 posted event to 0..1 reception line"),
            Rel("stock_reception_lines", "stock_reception_corrections"), Rel("stock_pools", "cutman_imports"), Rel("cutman_imports", "cutman_import_lines"),
            Rel("inventory_events", "cutman_import_lines", "1 event to 0..1 CutMan row"), Rel("inventory_events", "future_stock_arrivals", "0..1 receipt event to 0..1 arrival"),
            Rel("warehouse_delivery_instructions", "warehouse_delivery_instruction_lines"), Rel("warehouse_delivery_instructions", "delivery_codes"),
            Rel("delivery_codes", "delivery_code_access_events"), Rel("warehouse_delivery_instructions", "warehouse_delivery_documents", "1 to 0..1 generated document"),
            Rel("warehouse_delivery_documents", "warehouse_delivery_receipts", "1 to 0..* receipt submissions"),
            Rel("inventory_events", "warehouse_delivery_receipts", "1 posted event to 0..1 validated receipt"),
            Rel("inventory_postings", "v_inventory_balance", "ledger to projection", True),
            Rel("v_inventory_balance", "v_stock_summary", "location to pool rollup", True),
        ],
        notes=[
            N("Exactly-once posting", "The service inserts inventory_events and all postings atomically. Repeating an idempotency/source key with the same payload returns the existing result; a different payload hash is rejected. Posted rows cannot be updated/deleted. Corrections and cancellations create linked reversal events."),
            N("Pool scope and arithmetic", "project_stock_pools explicitly grants a project access to a pool: shared pools may have several active project mappings, while project-scoped pools have exactly one. CutMan imports name both project and pool and require an active mapping. Practical stock excludes transit; simulations separately snapshot warehouse, WIP, transit, and planned components."),
            N("Code and receipt gate", "Store only a slow-hash/digest of the human code. Successful generation consumes it once. A warehouse document may receive multiple signed submissions (for correction/retry), but partial unique indexes allow only one validated submission and only one inventory-posting submission for that document. Validation requires a typed signer record and posts the transfer exactly once."),
        ],
    ))

    pages.append(Page(
        "06 Customer Delivery/Finance",
        "Partial shipments, confirmation evidence, immutable price/transport snapshots, effective-dated rates, forecasts, and derived actuals.",
        nodes=[
            T("customer_delivery_instructions", "delivery", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK purchase_order_id uuid NOT NULL -> purchase_orders", "FK delivery_method_id uuid NOT NULL -> delivery_methods", "planned_delivery_date date NULL", "planned_period daterange NULL", "status customer_instruction_status NOT NULL", "FK generated_by uuid NOT NULL -> users", "generated_at timestamptz NOT NULL", "row_version bigint NOT NULL DEFAULT 1"),
            T("customer_delivery_instruction_lines", "delivery", "PK id uuid", "FK instruction_id uuid NOT NULL -> customer_delivery_instructions", "line_no integer NOT NULL", "FK po_item_id uuid NOT NULL -> purchase_order_items", "FK po_version_item_id uuid NOT NULL -> purchase_order_version_items", "fgpn_code_snapshot varchar(32) NOT NULL", "quantity_to_deliver numeric(20,4) NOT NULL", "UQ (instruction_id,line_no)", "UQ (instruction_id,po_item_id)", "CK quantity_to_deliver>0"),
            T("customer_delivery_documents", "delivery", "PK id uuid", "FK instruction_id uuid NOT NULL -> customer_delivery_instructions", "FK document_id uuid NOT NULL -> documents", "generated_at timestamptz NOT NULL", "UQ instruction_id", "UQ document_id"),
            T("customer_deliveries", "delivery", "PK id uuid", "FK instruction_id uuid NOT NULL -> customer_delivery_instructions", "FK project_id uuid NOT NULL -> projects", "shipment_no integer NOT NULL", "FK delivery_method_id uuid NOT NULL -> delivery_methods", "FK method_cost_record_id uuid NOT NULL -> delivery_method_cost_records", "transport_cost_snapshot numeric(20,4) NOT NULL", "transport_currency_snapshot char(3) NOT NULL", "planned_delivery_date date NULL", "actual_delivery_date date NULL", "status customer_delivery_status NOT NULL", "FK created_by uuid NOT NULL -> users", "created_at timestamptz NOT NULL", "row_version bigint NOT NULL DEFAULT 1", "UQ (instruction_id,shipment_no)", "CK method matches effective cost record; Delivered requires confirmation"),
            T("customer_delivery_lines", "delivery", "PK id uuid", "FK customer_delivery_id uuid NOT NULL -> customer_deliveries", "line_no integer NOT NULL", "FK po_item_id uuid NOT NULL -> purchase_order_items", "FK po_version_item_id uuid NOT NULL -> purchase_order_version_items", "FK fgpn_id uuid NOT NULL -> fgpns", "fgpn_code_snapshot varchar(32) NOT NULL", "delivered_level_snapshot varchar(40) NULL", "description_snapshot varchar(50) NULL", "delivered_quantity numeric(20,4) NOT NULL", "FK price_record_id uuid NOT NULL -> fgpn_price_records", "unit_price_snapshot numeric(20,4) NOT NULL", "currency_snapshot char(3) NOT NULL", "GEN delivery_value numeric(20,4)", "UQ (customer_delivery_id,line_no)", "CK qty>0; value=qty*price"),
            T("delivery_confirmations", "delivery", "PK id uuid", "FK customer_delivery_id uuid NOT NULL -> customer_deliveries", "confirmation_date date NOT NULL", "confirmation_method varchar(40) NOT NULL", "confirming_person_name varchar(150) NOT NULL", "FK evidence_document_id uuid NULL -> documents", "evidence_reference text NULL", "FK recorded_by uuid NOT NULL -> users", "recorded_at timestamptz NOT NULL", "UQ customer_delivery_id", "CK evidence_document OR evidence_reference required", "CK immutable"),
            T("fgpn_price_records", "finance", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "FK fgpn_id uuid NOT NULL -> fgpns", "part_number char(7) NULL", "description varchar(50) NULL", "trim_style varchar(40) NULL", "unit_price numeric(20,4) NOT NULL", "currency char(3) NOT NULL", "valid_during daterange NOT NULL", "FK created_by uuid NOT NULL -> users", "created_at timestamptz NOT NULL", "CK unit_price>=0", "EXCLUDE overlap (project_id,fgpn_id,valid_during)"),
            T("delivery_method_cost_records", "finance", "PK id uuid", "FK delivery_method_id uuid NOT NULL -> delivery_methods", "FK project_id uuid NULL -> projects", "cost_amount numeric(20,4) NOT NULL", "currency char(3) NOT NULL", "valid_during daterange NOT NULL", "FK created_by uuid NOT NULL -> users", "created_at timestamptz NOT NULL", "CK cost_amount>=0", "EXCLUDE overlap per method/project period"),
            T("material_cost_records", "finance", "PK id uuid", "FK material_id uuid NOT NULL -> materials", "FK project_id uuid NULL -> projects", "ordered_price numeric(20,4) NOT NULL", "currency char(3) NOT NULL", "valid_during daterange NOT NULL", "supplier_reference varchar(100) NULL", "FK entered_by uuid NOT NULL -> users", "entered_at timestamptz NOT NULL", "CK ordered_price>=0", "EXCLUDE overlap per material/project period"),
            T("sales_forecasts", "finance", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "forecast_month date NOT NULL", "version_no integer NOT NULL", "status forecast_status NOT NULL", "FK created_by uuid NOT NULL -> users", "created_at timestamptz NOT NULL", "UQ (project_id,forecast_month,version_no)", "CK forecast_month is first day", "CK active version immutable"),
            T("sales_forecast_lines", "finance", "PK id uuid", "FK forecast_id uuid NOT NULL -> sales_forecasts", "line_no integer NOT NULL", "FK purchase_order_id uuid NULL -> purchase_orders", "FK po_item_id uuid NULL -> purchase_order_items", "FK fgpn_id uuid NOT NULL -> fgpns", "planned_pickup_date date NOT NULL", "planned_quantity numeric(20,4) NOT NULL", "FK price_record_id uuid NOT NULL -> fgpn_price_records", "unit_price_snapshot numeric(20,4) NOT NULL", "currency_snapshot char(3) NOT NULL", "GEN forecast_value numeric(20,4)", "UQ (forecast_id,line_no)", "CK qty>=0; value=qty*price"),
            T("invoices", "finance", "PK id uuid", "FK customer_delivery_id uuid NOT NULL -> customer_deliveries", "FK document_id uuid NOT NULL -> documents", "invoice_number varchar(80) NULL", "status invoice_status NOT NULL", "FK uploaded_by uuid NOT NULL -> users", "uploaded_at timestamptz NOT NULL", "UQ document_id", "UQ NULLS NOT DISTINCT (customer_delivery_id,invoice_number)"),
            V("v_actual_sales", "finance", "confirmed delivery line only", "sale_date = confirmation/actual date", "quantity and unit_price_snapshot", "delivery_value + allocated transport snapshot", "no mutable actual_sales table"),
            V("v_period_revenue", "finance", "period / project / PO completion class", "SUM confirmed line delivery values", "PLUS transport cost snapshot once per shipment", "current and next month supported"),
            V("v_forecast_vs_actual", "finance", "month / project / FGPN", "forecast qty/value from active forecast", "actual qty/value from confirmations", "variance qty/value"),
        ],
        relations=[
            Rel("customer_delivery_instructions", "customer_delivery_instruction_lines"), Rel("customer_delivery_instructions", "customer_delivery_documents", "1 to 0..1 document"),
            Rel("customer_delivery_instructions", "customer_deliveries"), Rel("delivery_method_cost_records", "customer_deliveries"),
            Rel("customer_deliveries", "customer_delivery_lines"), Rel("fgpn_price_records", "customer_delivery_lines"),
            Rel("customer_deliveries", "delivery_confirmations", "1 to 0..1 explicit confirmation"),
            Rel("customer_deliveries", "invoices"), Rel("sales_forecasts", "sales_forecast_lines"),
            Rel("fgpn_price_records", "sales_forecast_lines"), Rel("customer_delivery_lines", "v_actual_sales", "confirmed lines only", True),
            Rel("delivery_confirmations", "v_actual_sales", "confirmation gate", True), Rel("v_actual_sales", "v_period_revenue", "period rollup", True),
            Rel("sales_forecast_lines", "v_forecast_vs_actual", "forecast side", True), Rel("v_actual_sales", "v_forecast_vs_actual", "actual side", True),
        ],
        notes=[
            N("Historical value invariant", "A shipment selects the effective delivery-method cost record and copies amount/currency. Each line selects the effective FGPN price record and copies price/currency. Later price or cost changes create new effective-dated rows and never change historical delivery or forecast values."),
            N("Confirmation/quantity gate", "A shipment becomes Delivered only when a delivery_confirmations row exists. A deferred trigger locks the delivery facts at confirmation and ensures cumulative confirmed quantity for each stable PO item does not exceed the current ordered quantity. The final PO status also requires remaining quantity zero."),
            N("Finance derivation", "Actual sales and revenue are views over confirmed immutable delivery snapshots, preventing duplicate accounting facts. Transport cost is added once per shipment, not once per line. Invoice mandatory/conditional behavior remains a policy setting until OP-11 is resolved."),
        ],
    ))

    pages.append(Page(
        "07 Audit/Alerts/Cross-cutting",
        "Tamper-evident audit streams, traceability packages, SRS dashboard exceptions, request idempotency, and transactional outbox.",
        nodes=[
            T("audit_stream_heads", "audit", "PK stream_key varchar(160)", "last_sequence_no bigint NOT NULL", "last_event_hash bytea NOT NULL", "updated_at timestamptz NOT NULL", "row_version bigint NOT NULL DEFAULT 1", "CK internal row locked FOR UPDATE during append"),
            T("audit_events", "audit", "PK id uuid", "stream_key varchar(160) NOT NULL", "sequence_no bigint NOT NULL", "FK project_id uuid NULL -> projects", "FK user_id uuid NULL -> users", "event_type varchar(80) NOT NULL", "entity_type varchar(80) NOT NULL", "entity_id uuid NOT NULL", "old_value jsonb NULL", "new_value jsonb NULL", "reason text NULL", "FK document_id uuid NULL -> documents", "occurred_at timestamptz NOT NULL", "prev_hash bytea NOT NULL", "event_hash bytea NOT NULL", "UQ (stream_key,sequence_no)", "UQ event_hash", "CK hash=sha256(prev_hash+canonical payload)", "CK append-only"),
            T("idempotency_requests", "cross", "PK id uuid", "scope varchar(80) NOT NULL", "idempotency_key uuid NOT NULL", "request_hash bytea NOT NULL", "status idempotency_status NOT NULL", "response_code integer NULL", "response_body jsonb NULL", "created_at timestamptz NOT NULL", "completed_at timestamptz NULL", "expires_at timestamptz NOT NULL", "UQ (scope,idempotency_key)", "CK key reuse requires same request_hash"),
            T("outbox_events", "audit", "PK id uuid", "FK audit_event_id uuid NULL -> audit_events", "aggregate_type varchar(80) NOT NULL", "aggregate_id uuid NOT NULL", "event_type varchar(100) NOT NULL", "topic varchar(120) NOT NULL", "payload jsonb NOT NULL", "occurred_at timestamptz NOT NULL", "available_at timestamptz NOT NULL", "published_at timestamptz NULL", "attempt_count integer NOT NULL DEFAULT 0", "last_error text NULL", "UQ audit_event_id", "UQ (aggregate_type,aggregate_id,event_type,occurred_at)"),
            T("dashboard_alerts", "audit", "PK id uuid", "FK project_id uuid NULL -> projects", "alert_type alert_type NOT NULL", "entity_type varchar(80) NOT NULL", "entity_id uuid NOT NULL", "severity alert_severity NOT NULL", "message text NOT NULL", "dedupe_key varchar(200) NOT NULL", "status alert_status NOT NULL", "created_at timestamptz NOT NULL", "FK acknowledged_by uuid NULL -> users", "acknowledged_at timestamptz NULL", "resolved_at timestamptz NULL", "UQ partial dedupe_key WHERE status='open'", "CK SRS exceptions only; no notification table"),
            T("audit_packages", "audit", "PK id uuid", "FK project_id uuid NOT NULL -> projects", "as_of_at timestamptz NOT NULL", "FK document_id uuid NOT NULL -> documents", "manifest_hash bytea NOT NULL", "status audit_package_status NOT NULL", "FK generated_by uuid NOT NULL -> users", "generated_at timestamptz NOT NULL", "UQ document_id", "UQ (project_id,as_of_at,manifest_hash)"),
            T("audit_package_items", "audit", "PK id uuid", "FK audit_package_id uuid NOT NULL -> audit_packages", "ordinal integer NOT NULL", "entity_type varchar(80) NOT NULL", "entity_id uuid NOT NULL", "FK document_id uuid NULL -> documents", "item_hash bytea NOT NULL", "included_at timestamptz NOT NULL", "UQ (audit_package_id,ordinal)", "UQ NULLS NOT DISTINCT (audit_package_id,entity_type,entity_id,document_id)"),
            T("traceability_links", "audit", "PK id uuid", "source_entity_type varchar(80) NOT NULL", "source_entity_id uuid NOT NULL", "target_entity_type varchar(80) NOT NULL", "target_entity_id uuid NOT NULL", "relationship_type varchar(80) NOT NULL", "created_at timestamptz NOT NULL", "UQ (source_entity_type,source_entity_id,target_entity_type,target_entity_id,relationship_type)", "CK append-only; validated entity-type registry"),
            V("v_project_lifecycle_audit", "audit", "project + PO versions/corrections/status", "BOM/simulation/policy/meeting minutes", "inventory + warehouse/customer deliveries", "confirmations/invoices/finance", "documents/signers and event hashes"),
            V("v_actionable_dashboard", "audit", "project-scoped RLS", "open alerts first", "stock <= threshold", "delivery confirmation overdue", "missing materials", "launch missing meeting minutes"),
        ],
        relations=[
            Rel("audit_stream_heads", "audit_events", "1 stream head to 0..* chained events"),
            Rel("audit_events", "outbox_events", "1 fact to 0..1 publication"),
            Rel("audit_events", "traceability_links", "facts may be linked", True),
            Rel("audit_packages", "audit_package_items"), Rel("audit_events", "v_project_lifecycle_audit", "event side", True),
            Rel("traceability_links", "v_project_lifecycle_audit", "relationship side", True),
            Rel("audit_package_items", "v_project_lifecycle_audit", "package projection", True),
            Rel("dashboard_alerts", "v_actionable_dashboard", "open exception projection", True),
        ],
        notes=[
            N("Append-only hash chain", "Only a SECURITY DEFINER append function can insert audit events. It locks audit_stream_heads, assigns the next sequence, canonicalizes the event payload, computes SHA-256(previous hash + payload), inserts the event, and advances the head in one transaction. UPDATE/DELETE/TRUNCATE are revoked; periodic external anchor/checkpoint is recommended."),
            N("Transactional outbox", "The business fact, audit event, and outbox row commit together. A worker publishes with retry and marks published_at; consumers deduplicate by outbox id. This avoids dual-write loss. outbox_events is integration plumbing, not a user notification subsystem."),
            N("Alerts and traceability", "dashboard_alerts is limited to SRS exception states and uses dedupe keys; current alert state may change, while its creation/acknowledgement/resolution actions are audit events. Polymorphic traceability_links are validated against a controlled entity-type registry; normal domain relations continue to use real FKs."),
            N("Database enforcement", "Use CHECK/UNIQUE/EXCLUDE/partial indexes for local invariants; deferred constraint triggers for same-project and cross-table workflow gates; RLS for project visibility; immutable-table privilege/trigger guards; pgcrypto digest functions; btree_gist for non-overlapping effective periods. All commands are transactionally idempotent."),
        ],
    ))
    return pages


def esc(value: str) -> str:
    from html import escape
    return escape(value, quote=False)


def field_html(value: str) -> str:
    first, _, rest = value.partition(" ")
    colors = {"PK": "#7F2420", "FK": "#1F4E79", "UQ": "#6A1B9A", "CK": "#2F6B2F", "IX": "#555555", "GEN": "#8A4B08"}
    if first in colors:
        return f'<span style="color:{colors[first]};font-weight:700">{first}</span> {esc(rest)}'
    return esc(value)


def node_value(node: Node) -> str:
    fill, stroke, dark = PALETTE.get(node.module, PALETTE["cross"])
    if node.kind == "note":
        return (f'<div style="font-family:Arial;color:{dark};font-size:13px;line-height:1.35">'
                f'<b>{esc(node.name)}</b><br><span style="font-size:11px">{esc(node.text)}</span></div>')
    if node.kind == "module":
        return (f'<div style="font-family:Arial;color:{dark};font-size:15px;line-height:1.35">'
                f'<b>{esc(node.name)}</b><br><span style="font-size:11px">{esc(node.text)}</span></div>')
    label = "VIEW / PROJECTION" if node.kind == "view" else "TABLE"
    field_rows = "<br>".join(field_html(v) for v in node.fields)
    return (f'<div style="font-family:Consolas,Arial;color:#263238;font-size:10px;line-height:1.35">'
            f'<div style="background-color:{fill};color:{dark};font-family:Arial;font-size:13px;padding:5px">'
            f'<b>{esc(node.name)}</b> <span style="font-size:9px">{label}</span></div>'
            f'<div style="padding:7px;text-align:left">{field_rows}</div></div>')


def node_height(node: Node, width: int = 420) -> int:
    if node.kind == "module":
        return 115
    if node.kind == "note":
        lines = max(3, math.ceil((len(node.text) + len(node.name)) / 105))
        return 55 + lines * 18
    chars = 57 if width >= 400 else 48
    lines = sum(max(1, math.ceil(len(f) / chars)) for f in node.fields)
    return 52 + lines * 17 + 14


def add_vertex(root: ET.Element, node_id: str, node: Node, x: int, y: int, w: int, h: int) -> ET.Element:
    fill, stroke, _ = PALETTE.get(node.module, PALETTE["cross"])
    if node.kind == "view":
        fill, stroke = "#F2F2F2", "#9E9E9E"
    style = ("rounded=1;whiteSpace=wrap;html=1;overflow=hidden;shadow=0;"
             f"fillColor={'#FFFFFF' if node.kind == 'table' else fill};strokeColor={stroke};"
             "strokeWidth=1.4;align=left;verticalAlign=top;spacing=0;")
    if node.kind == "note":
        style += "dashed=1;spacing=10;"
    if node.kind == "module":
        style += "spacing=12;"
    cell = ET.SubElement(root, "mxCell", {
        "id": node_id, "value": node_value(node), "style": style,
        "vertex": "1", "parent": "1", "dataKind": node.kind, "dataName": node.name,
    })
    ET.SubElement(cell, "mxGeometry", {"x": str(x), "y": str(y), "width": str(w), "height": str(h), "as": "geometry"})
    return cell


def add_edge(root: ET.Element, edge_id: str, rel: Rel, source_id: str, target_id: str) -> None:
    style = ("edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;"
             "startArrow=ERone;startFill=0;endArrow=ERmany;endFill=0;strokeWidth=1.1;"
             "strokeColor=#64748B;fontSize=10;labelBackgroundColor=#FFFFFF;")
    if rel.dashed:
        style += "dashed=1;"
    cell = ET.SubElement(root, "mxCell", {
        "id": edge_id, "value": esc(rel.label), "style": style, "edge": "1", "parent": "1",
        "source": source_id, "target": target_id, "dataKind": "relationship",
    })
    ET.SubElement(cell, "mxGeometry", {"relative": "1", "as": "geometry"})


def render_page(diagram: ET.Element, page: Page, page_index: int) -> tuple[int, int, int, int]:
    model = ET.SubElement(diagram, "mxGraphModel", {
        "dx": "1600", "dy": "1000", "grid": "1", "gridSize": "10", "guides": "1",
        "tooltips": "1", "connect": "1", "arrows": "1", "fold": "1", "page": "1",
        "pageScale": "1", "pageWidth": "2600", "pageHeight": "2400", "math": "0", "shadow": "0",
    })
    graph = ET.SubElement(model, "root")
    ET.SubElement(graph, "mxCell", {"id": "0"})
    ET.SubElement(graph, "mxCell", {"id": "1", "parent": "0"})

    title = Node(page.name, "cross", (), "module", page.subtitle)
    add_vertex(graph, f"p{page_index}_title", title, 40, 25, 2520, 72)
    # Make title visually distinct.
    title_cell = graph[-1]
    title_cell.set("style", "rounded=1;whiteSpace=wrap;html=1;fillColor=#EAF0F6;strokeColor=#52677A;strokeWidth=2;align=left;verticalAlign=middle;spacing=14;")

    ids: dict[str, str] = {}
    cols = 5
    card_w, gap_x, gap_y = 420, 85, 55
    start_x, y = 40, 125
    rows = [page.nodes[i:i + cols] for i in range(0, len(page.nodes), cols)]
    counter = 0
    for row in rows:
        heights = [node_height(n, card_w) for n in row]
        row_h = max(heights, default=0)
        for c, (node, h) in enumerate(zip(row, heights)):
            node_id = f"p{page_index}_n{counter}"
            add_vertex(graph, node_id, node, start_x + c * (card_w + gap_x), y, card_w, h)
            if node.name in ids:
                raise ValueError(f"Duplicate node name on page {page.name}: {node.name}")
            ids[node.name] = node_id
            counter += 1
        y += row_h + gap_y

    if page.notes:
        y += 15
        note_w, note_gap = 1215, 90
        for i in range(0, len(page.notes), 2):
            pair = page.notes[i:i + 2]
            heights = [node_height(n, note_w) for n in pair]
            row_h = max(heights)
            for c, (node, h) in enumerate(zip(pair, heights)):
                node_id = f"p{page_index}_note{i+c}"
                add_vertex(graph, node_id, node, 40 + c * (note_w + note_gap), y, note_w, h)
            y += row_h + 35

    for i, rel in enumerate(page.relations):
        if rel.parent not in ids or rel.child not in ids:
            raise ValueError(f"Missing endpoint on {page.name}: {rel.parent} -> {rel.child}")
        add_edge(graph, f"p{page_index}_e{i}", rel, ids[rel.parent], ids[rel.child])

    model.set("pageHeight", str(max(2400, y + 100)))
    tables = sum(n.kind == "table" for n in page.nodes)
    views = sum(n.kind == "view" for n in page.nodes)
    return tables, views, len(page.relations), len(page.notes)


def validate_foreign_key_annotations(pages: Iterable[Page]) -> dict[str, int]:
    """Fail generation when a textual FK annotation names an undefined table."""
    page_list = list(pages)
    table_nodes = [
        node
        for page in page_list
        for node in page.nodes
        if node.kind == "table"
    ]
    table_names = {node.name for node in table_nodes}
    duplicate_tables = sorted({name for name in table_names if sum(n.name == name for n in table_nodes) > 1})
    tables_without_pk = sorted(
        node.name for node in table_nodes
        if not any(field_value.startswith("PK ") for field_value in node.fields)
    )
    annotated_foreign_keys = 0
    malformed: list[str] = []
    missing: list[str] = []
    target_pattern = re.compile(r"->\s*([A-Za-z_][A-Za-z0-9_]*)")

    for page in page_list:
        for node in page.nodes:
            if node.kind != "table":
                continue
            for field_value in node.fields:
                targets = target_pattern.findall(field_value)
                if field_value.startswith("FK ") and not targets:
                    malformed.append(f"{node.name}: {field_value}")
                for target in targets:
                    annotated_foreign_keys += 1
                    if target not in table_names:
                        missing.append(f"{node.name} -> {target}")

    if duplicate_tables:
        raise ValueError("Duplicate table names: " + ", ".join(duplicate_tables))
    if tables_without_pk:
        raise ValueError("Tables without PK annotations: " + ", ".join(tables_without_pk))
    if malformed:
        raise ValueError("Malformed FK annotations: " + "; ".join(malformed))
    if missing:
        raise ValueError("Undefined FK targets: " + "; ".join(missing))
    return {
        "tables_defined": len(table_names),
        "duplicate_tables": 0,
        "tables_without_pk": 0,
        "annotated_foreign_keys": annotated_foreign_keys,
        "missing_fk_targets": 0,
    }


def generate(output: Path, pages: list[Page] | None = None) -> dict[str, int]:
    pages = build_pages() if pages is None else pages
    validate_foreign_key_annotations(pages)
    mxfile = ET.Element("mxfile", {
        "host": "app.diagrams.net", "modified": datetime.now(timezone.utc).isoformat(),
        "agent": "OpenAI Codex - Launch System ERD generator", "version": "24.7.17",
        "type": "device", "compressed": "false",
    })
    totals = {"pages": 0, "tables": 0, "views": 0, "edges": 0, "notes": 0}
    for i, page in enumerate(pages):
        diagram = ET.SubElement(mxfile, "diagram", {"id": f"launch-page-{i:02d}", "name": page.name})
        t, v, e, n = render_page(diagram, page, i)
        totals["pages"] += 1
        totals["tables"] += t
        totals["views"] += v
        totals["edges"] += e
        totals["notes"] += n

    tree = ET.ElementTree(mxfile)
    ET.indent(tree, space="  ")
    output.parent.mkdir(parents=True, exist_ok=True)
    tree.write(output, encoding="utf-8", xml_declaration=True)
    return totals


def validate(output: Path, expected_pages: int = 8) -> dict[str, int]:
    root = ET.parse(output).getroot()
    if root.tag != "mxfile":
        raise ValueError("Root must be mxfile")
    diagrams = root.findall("diagram")
    if len(diagrams) != expected_pages:
        raise ValueError(f"Expected {expected_pages} pages, found {len(diagrams)}")
    counts = {"pages": len(diagrams), "tables": 0, "views": 0, "edges": 0, "notes": 0}
    for diagram in diagrams:
        graph = diagram.find("mxGraphModel/root")
        if graph is None:
            raise ValueError(f"Page {diagram.get('name')} has no mxGraphModel/root")
        cells = graph.findall("mxCell")
        ids = {c.get("id") for c in cells}
        if not {"0", "1"}.issubset(ids):
            raise ValueError(f"Page {diagram.get('name')} lacks base cells")
        if len(ids) != len(cells):
            raise ValueError(f"Duplicate mxCell ids on page {diagram.get('name')}")
        for c in cells:
            kind = c.get("dataKind")
            if kind == "table": counts["tables"] += 1
            elif kind == "view": counts["views"] += 1
            elif kind == "note": counts["notes"] += 1
            if c.get("edge") == "1":
                counts["edges"] += 1
                if c.get("source") not in ids or c.get("target") not in ids:
                    raise ValueError(f"Dangling edge {c.get('id')} on page {diagram.get('name')}")
    return counts


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("launch_system_optimized.drawio"))
    args = parser.parse_args()
    pages = build_pages()
    fk_validation = validate_foreign_key_annotations(pages)
    generated = generate(args.output.resolve(), pages)
    validated = validate(args.output.resolve())
    if generated != validated:
        raise RuntimeError(f"Generated/validated counts differ: {generated} != {validated}")
    print(f"Wrote: {args.output.resolve()}")
    print("Validated XML: " + ", ".join(f"{k}={v}" for k, v in validated.items()))
    print("Validated FK annotations: " + ", ".join(f"{k}={v}" for k, v in fk_validation.items()))


if __name__ == "__main__":
    main()
